version: '3'
 
services:
  nginx:
    restart: always
    image: nginx:1.21.0
    container_name: nginx
    volumes:
      - ./volume:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.entrypoints=http"
      - "traefik.http.routers.website.rule=Host(`${URL}`)"
      - "traefik.http.middlewares.website-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.website.middlewares=website-https-redirect"
      - "traefik.http.routers.website-secure.entrypoints=https"
      - "traefik.http.routers.website-secure.rule=Host(`${URL}`)"
      - "traefik.http.routers.website-secure.tls=true"
      - "traefik.http.routers.website-secure.tls.certresolver=http"
      - "traefik.http.routers.website-secure.service=website"
      - "traefik.http.services.website.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
     - "proxy"

networks:
  proxy:
    external: true



